install.packages("calibrate")
install.packages("FNN")
install.packages('ggplot2', dependencies=TRUE)
# install.packages("quantmod")
install.packages("RODBC")
install.packages("rgl") #      , repos="http://R-Forge.R-project.org")
install.packages("scatterplot3d")
